packages:
  - "apps/*"
  - "packages/*"
  - "../kb-labs-devkit"
  - "../kb-labs-devlink/packages/*"
  - "../kb-labs-mind"
  - "../kb-labs-mind/packages/*"
  - "../kb-labs-audit/packages/*"
  - "../kb-labs-shared/packages/*"
  - "../kb-labs-core/packages/*"
  - "../kb-labs-release-manager/packages/*"
