name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/.vscode/**'
      - '**/.idea/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    uses: KirillBaranov/kb-labs-devkit/.github/workflows/ci.yml@main
    with:
      node-version: '20'